apiVersion: v1
kind: Service
metadata:
  name: task-manager-service
spec:
  selector:
    app: task-manager
  type: LoadBalancer     # Use ClusterIP if you don't have a cloud LB (minikube uses NodePort)
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
